{'name': 'Hair Purchasing Foundation',
 'version': '20.0.1.0.0',
 'category': 'Purchases',
 'author': 'IdeaCode Academy',
 'license': 'LGPL-3',
 'depends': ['base'],
 'data': ['security/hair_base_groups.xml',
          'security/ir.access.csv',
          'security/hair_master_security.xml',
          'views/hair_type_views.xml',
          'views/hair_texture_views.xml',
          'views/hair_color_views.xml',
          'views/hair_grade_views.xml',
          'views/hair_length_views.xml',
          'views/hair_base_menus.xml'],
 'demo': ['demo/hair_master_demo.xml'],
 'application': True,
 'installable': True}
