import math
from decimal import Decimal

from odoo import api, fields, models
from odoo.exceptions import AccessError, ValidationError


class HairPurchase(models.Model):
    _name = 'hair.purchase'
    _description = 'Hair Purchase Intake'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'date desc, id desc'
    _check_company_auto = True

    name = fields.Char(required=True, readonly=True, copy=False, default='New', index=True)
    date = fields.Datetime(required=True, default=fields.Datetime.now, tracking=True)
    company_id = fields.Many2one('res.company', required=True, default=lambda self: self.env.company, index=True, ondelete='restrict')
    seller_id = fields.Many2one('res.partner', required=True, check_company=True, ondelete='restrict', tracking=True,
                                domain="[('hair_is_seller', '=', True), ('company_id', '=', company_id)]")
    buyer_id = fields.Many2one('res.users', required=True, default=lambda self: self.env.user, check_company=True, ondelete='restrict')
    currency_id = fields.Many2one(related='company_id.currency_id')
    state = fields.Selection([('draft', 'Draft')], default='draft', required=True, readonly=True, copy=False)
    line_ids = fields.One2many('hair.purchase.line', 'purchase_id', copy=True)
    payable_weight = fields.Float('Payable Weight (kg)', compute='_compute_payable_weight', store=True, digits=(16, 3))
    notes = fields.Text()

    _name_unique = models.Constraint('UNIQUE(name, company_id)', 'Purchase references must be unique within a company.')

    @api.depends('line_ids.payable_weight')
    def _compute_payable_weight(self):
        for purchase in self:
            purchase.payable_weight = math.fsum(purchase.line_ids.mapped('payable_weight'))

    @api.constrains('seller_id', 'company_id')
    def _check_seller(self):
        for purchase in self:
            if not purchase.seller_id.hair_is_seller or purchase.seller_id.company_id != purchase.company_id:
                raise ValidationError(self.env._('Select a hair seller belonging to the purchase company.'))

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            self._check_derived_values(vals)
            self._check_company_permission(vals.get('company_id', self.env.company.id))
            if vals.get('state', 'draft') != 'draft':
                raise ValidationError(self.env._('Only draft intake is available.'))
            # References are generated by the server, including imports and RPC calls.
            vals['name'] = self.env['ir.sequence'].with_company(vals.get('company_id', self.env.company.id)).next_by_code('hair.purchase')
        return super().create(vals_list)

    def write(self, vals):
        self._check_derived_values(vals)
        if 'name' in vals or 'state' in vals:
            raise ValidationError(self.env._('Purchase references and lifecycle cannot be changed directly.'))
        if 'company_id' in vals:
            self._check_company_permission(vals['company_id'])
            if any(purchase.line_ids and purchase.company_id.id != vals['company_id'] for purchase in self):
                raise ValidationError(self.env._('Create a new intake to change the company after adding hair lines.'))
        return super().write(vals)

    def _write_workflow(self, vals):
        # Private action-only write; no caller-controlled context bypass.
        return super().write(vals)

    def _check_company_permission(self, company_id):
        if not self.env.su and company_id not in self.env.companies.ids:
            raise AccessError(self.env._('You cannot manage purchases for this company.'))

    def _check_derived_values(self, vals):
        if {'payable_weight', 'currency_id'} & vals.keys():
            raise ValidationError(self.env._('Calculated weight and currency cannot be entered manually.'))


class HairPurchaseLine(models.Model):
    _name = 'hair.purchase.line'
    _description = 'Hair Purchase Intake Line'
    _order = 'sequence, id'
    _check_company_auto = True

    purchase_id = fields.Many2one('hair.purchase', required=True, ondelete='cascade', index=True, check_company=True)
    company_id = fields.Many2one(related='purchase_id.company_id', store=True, index=True)
    sequence = fields.Integer(default=10)
    description = fields.Char()
    hair_type_id = fields.Many2one('hair.type', check_company=True, ondelete='restrict')
    texture_id = fields.Many2one('hair.texture', check_company=True, ondelete='restrict')
    color_id = fields.Many2one('hair.color', check_company=True, ondelete='restrict')
    length_id = fields.Many2one('hair.length', check_company=True, ondelete='restrict')
    gross_weight = fields.Float('Gross Weight (kg)', digits=(16, 3))
    tare_weight = fields.Float('Tare Weight (kg)', digits=(16, 3))
    waste_weight = fields.Float('Waste Weight (kg)', digits=(16, 3))
    moisture_weight = fields.Float('Moisture Deduction (kg)', digits=(16, 3))
    other_weight = fields.Float('Other Deduction (kg)', digits=(16, 3))
    payable_weight = fields.Float('Payable Weight (kg)', compute='_compute_payable_weight', store=True, digits=(16, 3))

    @api.depends('gross_weight', 'tare_weight', 'waste_weight', 'moisture_weight', 'other_weight')
    def _compute_payable_weight(self):
        for line in self:
            # Decimal strings avoid binary-float cancellation at the scale resolution.
            values = [line.gross_weight, line.tare_weight, line.waste_weight, line.moisture_weight, line.other_weight]
            line.payable_weight = float(Decimal(str(values[0])) - sum(Decimal(str(value)) for value in values[1:]))

    @api.constrains('gross_weight', 'tare_weight', 'waste_weight', 'moisture_weight', 'other_weight')
    def _check_weights(self):
        for line in self:
            values = [line.gross_weight, line.tare_weight, line.waste_weight, line.moisture_weight, line.other_weight]
            if any(not math.isfinite(value) or value < 0 for value in values):
                raise ValidationError(self.env._('Weights must be finite and nonnegative.'))
            if sum(Decimal(str(value)) for value in values[1:]) > Decimal(str(values[0])):
                raise ValidationError(self.env._('Weight deductions cannot exceed gross weight.'))

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            self._check_weight_values(vals)
            self._check_purchase_permission(vals.get('purchase_id', self.env.context.get('default_purchase_id')))
        return super().create(vals_list)

    def write(self, vals):
        self._check_weight_values(vals)
        if 'purchase_id' in vals:
            self._check_purchase_permission(vals['purchase_id'])
        return super().write(vals)

    def _write_quality(self, vals):
        return super().write(vals)

    def _check_purchase_permission(self, purchase_id):
        if purchase_id:
            self.env['hair.purchase'].browse(purchase_id).check_access('write')

    def _check_weight_values(self, vals):
        if {'payable_weight', 'company_id'} & vals.keys():
            raise ValidationError(self.env._('Calculated weight and line company cannot be entered manually.'))
        # Validate before Float cache rounding, which cannot handle infinity/NaN.
        for name in ('gross_weight', 'tare_weight', 'waste_weight', 'moisture_weight', 'other_weight'):
            if name in vals:
                value = float(vals[name] or 0)
                if not math.isfinite(value) or value < 0:
                    raise ValidationError(self.env._('Weights must be finite and nonnegative.'))
