[options]
;
; Odoo configuration file
;
; This file is used by Odoo to configure the system.
;
; For more information, please visit: https://www.odoo.com/documentation/20.0/administration/odoo_docker.html
;

; Database configuration
db_host = odoo-db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = postgres

; Server configuration
http_host = 0.0.0.0
http_port = 8069

; Mailer configuration (set these in the UI)
email_from =
email_reply_to =

; Security
list_db = True

; Logging
log_level = info
log_file = /home/odoo/odoo.log

; Addon path
addons_path = /mnt/omnidoc/addons:/mnt/omnidoc/custom_addons